### ISSUE TITLE
Feature Request: Bot should decide when the PR goes stale/unresponsive after min number of days

### ISSUE THREAD

**Issue by harsha509** [SeleniumHQ/selenium-assistant#3]
### Description

The bot should comment on a PR if the PR goes unresponsive after 15 (or) 30 days. and can request any member to re submit the PR

### Motivation and Context

This will allow other contributors to decide whether to update the stale PR after it goes stale.

This is just an idea. Please suggest

**Comment by diemol** [comment]
This was closed by mistake since there were no issue templates here yet. Got that fixed now.
