### ISSUE TITLE
Firefox instances are not opening more than 5 instances inside container in docker

### ISSUE THREAD

**Issue by lakshminagandla** [SeleniumHQ/selenium-assistant#7]
## 🐛 Bug Report

Firefox instances are not opening more than 5 instances inside container in docker though we have provided node instances and session instance are more.

We have used below command to create firefox node debug setup

docker run -d -p 5903:5900 --link selenium-hub:hub -v /dev/shm:/dev/shm -e NODE_MAX_INSTANCES=15 -e NODE_MAX_SESSION=15 selenium/node-firefox-debug:3.141.59-20200409

To open firefox instance I have used below code 

DesiredCapabilities capabilities = DesiredCapabilities.firefox(); capabilities.setCapability("unexpectedAlertBehaviour", "ignore"); //capabilities.setPlatform(Platform.fromString(os.toUpperCase())); capabilities.setCapability("maxDuration", 3600); driver = new RemoteWebDriver(hubURL, capabilities); 

## Expected behavior

Firefox should open with 15 instances docker container.

**Comment by lakshminagandla** [comment]
> ## 🐛 Bug Report
> Firefox instances are not opening more than 5 instances inside container in docker though we have provided node instances and session instance are more.
> 
> Steps to reproduce the behavior:
> 
> We have used below command to create firefox node debug setup
> 
> docker run -d -p 5903:5900 --link selenium-hub:hub -v /dev/shm:/dev/shm -e NODE_MAX_INSTANCES=15 -e NODE_MAX_SESSION=15 selenium/node-firefox-debug:3.141.59-20200409
> 
> To open firefox instance I have used below code
> 
> DesiredCapabilities capabilities = DesiredCapabilities.firefox(); capabilities.setCapability("unexpectedAlertBehaviour", "ignore"); //capabilities.setPlatform(Platform.fromString(os.toUpperCase())); capabilities.setCapability("maxDuration", 3600); driver = new RemoteWebDriver(hubURL, capabilities);
> 
> ## Expected behavior
> Firefox should open with 15 instances docker container.
> 
> A clear and concise description of what you expected to happen.

Can you please help on this issue once. when we are trying to launch firefox in two containers as well, still 5 instances are lauching in both containers (Container1 3nodes + Container2 2nodes).

**Comment by diemol** [comment]
The correct repository for docker selenium is https://github.com/SeleniumHQ/docker-selenium
But when creating an issue, please fill out the complete template, otherwise the bot will just close the issue.

**Comment by diemol** [comment]
If it was a question, please reach out to the shown contact points in the closed issues.
