### ISSUE TITLE
Jenkins error with chrome: Chrome failed to start: exited abnormally (unknown error: DevToolsActivePort file doesn't exist)

### ISSUE THREAD

**Issue by DB8851** [SeleniumHQ/selenium-assistant#8]
Hey,
I am trying to build my selenium test code through Jenkins but below error is encountered(chrome browser not opening), pls help to fix:
 
error is: 
unknown error: Chrome failed to start: exited abnormally
(unknown error: DevToolsActivePort file doesn't exist)
(The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'stayprime-Lenovo-ideapad-330-15IKB', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.3.0-40-generic', java.version: '11.0.6'
Driver info: driver.version: ChromeDriver
remote stacktrace: #0 0x555af40ca479

## To Reproduce
Write a test case(simple test like: open browser and navigate to any  URL)  using TestNG file>> now go to Jenkins and import the same project in Jenkins >>try to build >>observe(error code attached in above)

## Expected behavior
The browser should be open and navigate to expected URL)

Testing environment:
O.S version: Ubuntu 18.04.2 LTS
Chrome version: Version 79.0.3945.88 (Official Build) (64-bit)
Chrome driver version: 79.0.3945.36
Programming Language: JAVA
Project: Eclipse Maven project
Testing Framework: TestNG

Looking for your kindly support.

**Comment by DB8851** [comment]
let me know why this issue closed..??

**Comment by diemol** [comment]
Two reasons:
- This repo is not for Selenium issues, please head to SeleniumHQ/selenium
- There is an issue template, if it is ignored, the bot sees that and closes the issue.
